import type { SatisRaporSatiri } from '@/admin/baslat-menusu/raporlar/satis-ortak/tipler';

function gunOffset(gun: number, saat: number, dakika: number) {
  const d = new Date();
  d.setDate(d.getDate() - gun);
  d.setHours(saat, dakika, 0, 0);
  return d.toISOString();
}

export const ORNEK_SATISLAR: SatisRaporSatiri[] = [
  {
    id: 's1',
    tarihSaat: gunOffset(0, 12, 15),
    masa: '12',
    personel: 'Ahmet',
    urun: 'Mega Tavuk Döner Menü',
    urunGrubu: 'Döner Menü',
    miktar: 2,
    fiyat: 285,
    tutar: 570,
    sube: 'Merkez',
    departman: 'Salon',
  },
  {
    id: 's2',
    tarihSaat: gunOffset(0, 12, 18),
    masa: '12',
    personel: 'Ahmet',
    urun: 'Kola (330 Ml.)',
    urunGrubu: 'İçecek',
    miktar: 2,
    fiyat: 45,
    tutar: 90,
    sube: 'Merkez',
    departman: 'Salon',
  },
  {
    id: 's3',
    tarihSaat: gunOffset(0, 13, 40),
    masa: '7',
    personel: 'Elif',
    urun: 'Zurna Et Döner Menü',
    urunGrubu: 'Döner Menü',
    miktar: 1,
    fiyat: 395,
    tutar: 395,
    sube: 'Merkez',
    departman: 'Salon',
  },
  {
    id: 's4',
    tarihSaat: gunOffset(0, 18, 5),
    masa: '3',
    personel: 'Murat',
    urun: 'İskender Et Döner',
    urunGrubu: 'Et Döner',
    miktar: 1,
    fiyat: 320,
    tutar: 320,
    sube: 'Merkez',
    departman: 'Salon',
  },
  {
    id: 's5',
    tarihSaat: gunOffset(0, 19, 22),
    masa: 'Paket-8',
    personel: 'Zeynep',
    urun: 'Lavaş Arası Tavuk Döner',
    urunGrubu: 'Dürüm',
    miktar: 3,
    fiyat: 165,
    tutar: 495,
    sube: 'Merkez',
    departman: 'Paket',
  },
  {
    id: 's6',
    tarihSaat: gunOffset(1, 20, 10),
    masa: '5',
    personel: 'Can',
    urun: 'Combo Zurna Tavuk Dürüm Menü',
    urunGrubu: 'Döner Menü',
    miktar: 1,
    fiyat: 375,
    tutar: 375,
    sube: 'Şube Kadıköy',
    departman: 'Salon',
  },
  {
    id: 's7',
    tarihSaat: gunOffset(1, 21, 45),
    masa: '9',
    personel: 'Elif',
    urun: 'Patates Kızartması',
    urunGrubu: 'Yan Ürün',
    miktar: 2,
    fiyat: 75,
    tutar: 150,
    sube: 'Şube Kadıköy',
    departman: 'Salon',
  },
  {
    id: 's8',
    tarihSaat: gunOffset(2, 14, 30),
    masa: '15',
    personel: 'Ahmet',
    urun: 'Baklava (3 Adet)',
    urunGrubu: 'Tatlı',
    miktar: 1,
    fiyat: 120,
    tutar: 120,
    sube: 'Merkez',
    departman: 'Salon',
  },
];

export const SATIS_SUBELER = ['Tümü', 'Merkez', 'Şube Kadıköy'] as const;
export const SATIS_DEPARTMANLAR = ['Tümü', 'Salon', 'Paket', 'Trendyol'] as const;
