/** Panel modulleri — sube DB'de moduller tablosu yok; sanal liste olarak kullanilir */
export const PANEL_MODULLERI = [
  { modulAdi: 'Master', prefix: 'master' },
  { modulAdi: 'Kullanicilar', prefix: 'kullanicilar' },
  { modulAdi: 'Roller', prefix: 'roller' },
  { modulAdi: 'Tanimlar', prefix: 'tanimlar' },
  { modulAdi: 'Urunler Tanimlari', prefix: 'urunler_tanimlari' },
  { modulAdi: 'Menu Tanimlari', prefix: 'menu_tanimlari' },
  { modulAdi: 'Cari Tanimlari', prefix: 'cari_tanimlari' },
  { modulAdi: 'Yazici Tanimlari', prefix: 'yazici_tanimlari' },
  { modulAdi: 'Happy Hour Fiyat Listeleri', prefix: 'happy_hour_fiyat_listeleri' },
  { modulAdi: 'Tarilacak Urunler', prefix: 'tarilacak_urunler' },
  { modulAdi: 'Favoriler', prefix: 'favoriler' },
  { modulAdi: 'Odeme Gruplari', prefix: 'odeme_gruplari' },
  { modulAdi: 'Urun Eslestir', prefix: 'urun_eslestir' },
  { modulAdi: 'E Fatura Ayarlari', prefix: 'e_fatura_ayarlari' },
  { modulAdi: 'Marslanacak Urunler', prefix: 'marslanacak_urunler' },
  { modulAdi: 'Gun Sonu', prefix: 'gun_sonu' },
  { modulAdi: 'Gunluk Toplamlar', prefix: 'gunluk_toplamlar' },
  { modulAdi: 'Ozet Ciro', prefix: 'ozet_ciro' },
  { modulAdi: 'Masalara Gore Ciro', prefix: 'masalara_gore_ciro' },
  { modulAdi: 'Personel Tahsilat Raporu', prefix: 'personel_tahsilat_raporu' },
  { modulAdi: 'Faaliyet Raporu', prefix: 'faaliyet_raporu' },
  { modulAdi: 'Aktif Masalar', prefix: 'aktif_masalar' },
  { modulAdi: 'Fiyat Listesi', prefix: 'fiyat_listesi' },
  { modulAdi: 'Gider Gelir Kayitlari Raporu', prefix: 'gider_gelir_kayitlari_raporu' },
  { modulAdi: 'Acik Hesap Listesi', prefix: 'acik_hesap_listesi' },
  { modulAdi: 'Silinen Siparisler', prefix: 'silinen_siparisler' },
  { modulAdi: 'Satis Raporu', prefix: 'satis_raporu' },
  { modulAdi: 'Satis Toplamlari', prefix: 'satis_toplamlari' },
  { modulAdi: 'Ozel Raporlar', prefix: 'ozel_raporlar' },
  { modulAdi: 'Paket Servisi Gun Sonu', prefix: 'ps_gun_sonu' },
  { modulAdi: 'Eski Tahsilat Tarama', prefix: 'ps_eski_tahsilat_tarama' },
  { modulAdi: 'Paket Servisi Satis Raporu', prefix: 'ps_satis_raporu' },
  { modulAdi: 'Paket Servisi Satis Toplamlari', prefix: 'ps_satis_toplamlari' },
  { modulAdi: 'Paket Restoran Birlesik Gun Sonu', prefix: 'ps_paket_restoran_birlesik_gun_sonu' },
  { modulAdi: 'Rezervasyon Listesi', prefix: 'rezervasyon_listesi' },
  { modulAdi: 'Arctos Db Ayarlari', prefix: 'arctos_db_ayarlari' },
  { modulAdi: 'Firma Donem Secimi', prefix: 'firma_donem_secimi' },
  { modulAdi: 'Lisans Ayarlari', prefix: 'lisans_ayarlari' },
  { modulAdi: 'Ozellestirme', prefix: 'ozellestirme' },
  { modulAdi: 'Web Api Ayarlari', prefix: 'web_api_ayarlari' },
  { modulAdi: 'Ayarlar', prefix: 'ayarlar' },
  { modulAdi: 'Sekme Yonetimi', prefix: 'sekme_yonetimi' },
  { modulAdi: 'Kisayol Ayarlari', prefix: 'kisayol_ayarlari' },
  { modulAdi: 'Loglar', prefix: 'loglar' },
  { modulAdi: 'Veri Yedekleme', prefix: 'veri_yedekleme' },
] as const;

export function sanalModulListesi() {
  return PANEL_MODULLERI.map((m, i) => ({
    id: i + 1,
    modulAdi: m.modulAdi,
    prefix: m.prefix,
    durum: true,
  }));
}
