import type { UrunTanimlariKayit } from '@/admin/baslat-menusu/urunler-tanimlari/tipler';

export function varsayilanUrunTanimlariKaydi(): UrunTanimlariKayit {
  return {
    urunler: [
      {
        id: 'u1',
        stokKodu: '00000',
        ad: 'Combo Zurna Tavuk Dürüm Menü',
        sira: 1,
        kdvDahilFiyat: 375,
        kdvOrani: 10,
        istisnaKodu: '',
        urunGrubu: 'Trendyol',
        urunTipi: 'Combo',
        faturaGrubu: 'Yiyecek',
        favori: 'Yok',
        resimUrl: null,
        ikram: false,
        plu: '',
        ozelMatrahKodu: '',
        fiyatListeleri: [{ listeAdi: 'PAKET', fiyat: 390 }],
        secenekKategorileri: [
          { id: 'kat-1', sira: 1, kategori: 'İçecek', enAzSecim: 0, enFazlaSecim: 1 },
          { id: 'kat-2', sira: 2, kategori: 'Ekstra', enAzSecim: 0, enFazlaSecim: 3 },
          { id: 'kat-3', sira: 3, kategori: 'Porsiyon', enAzSecim: 1, enFazlaSecim: 1 },
        ],
        seviye1: [
          { id: 's1-1', sira: 1, secim: 'Tavuk Dürüm', fiyat: 0, fiyatListeleri: [] },
          { id: 's1-2', sira: 2, secim: 'Ayran', fiyat: 0, fiyatListeleri: [] },
        ],
        seviye2: [
          { id: 's2-1', sira: 1, secim: '120 gram', fiyat: 0, fiyatListeleri: [] },
          { id: 's2-2', sira: 2, secim: 'Tek Lavaş', fiyat: 0, fiyatListeleri: [{ listeAdi: 'PAKET', fiyat: 5 }] },
        ],
        secenekler: [
          {
            id: 'o1',
            sira: 1,
            secenekAdi: 'Fanta (330 Ml.)',
            kategori: 'İçecek',
            fiyat: 15,
            miktarli: false,
            fiyatListeleri: [],
          },
          {
            id: 'o2',
            sira: 2,
            secenekAdi: 'Tek Lavaş',
            kategori: 'Ekstra',
            fiyat: 10,
            miktarli: true,
            fiyatListeleri: [],
          },
          {
            id: 'o3',
            sira: 3,
            secenekAdi: '120 gram',
            kategori: 'Porsiyon',
            fiyat: 0,
            miktarli: false,
            fiyatListeleri: [],
          },
        ],
      },
      {
        id: 'u2',
        stokKodu: '00001',
        ad: 'Tiktok Tavuk Döner Dürüm - 80 gr.',
        sira: 2,
        kdvDahilFiyat: 185,
        kdvOrani: 10,
        istisnaKodu: '',
        urunGrubu: 'Dürüm',
        urunTipi: 'Normal',
        faturaGrubu: 'Yiyecek',
        favori: 'Garson',
        resimUrl: null,
        ikram: false,
        plu: 'PLU-801',
        ozelMatrahKodu: '',
        fiyatListeleri: [],
        secenekKategorileri: [],
        seviye1: [],
        seviye2: [],
        secenekler: [],
      },
      {
        id: 'u3',
        stokKodu: '00002',
        ad: 'Kola (330 Ml.)',
        sira: 3,
        kdvDahilFiyat: 45,
        kdvOrani: 10,
        istisnaKodu: '',
        urunGrubu: 'İçecek',
        urunTipi: 'Normal',
        faturaGrubu: 'İçecek',
        favori: 'Kasa',
        resimUrl: null,
        ikram: false,
        plu: '',
        ozelMatrahKodu: '',
        fiyatListeleri: [],
        secenekKategorileri: [],
        seviye1: [],
        seviye2: [],
        secenekler: [],
      },
    ],
  };
}
