import type { PsSatisRaporSatiri } from '@/admin/baslat-menusu/paket-servisi-raporlari/ps-satis-raporu/tipler';

function gunOffset(gun: number, saat: number, dakika: number) {
  const d = new Date();
  d.setDate(d.getDate() - gun);
  d.setHours(saat, dakika, 0, 0);
  return d.toISOString();
}

export const ORNEK_PS_SATISLAR: PsSatisRaporSatiri[] = [
  {
    id: 'ps1',
    tarihSaat: gunOffset(0, 11, 20),
    musteriAdi: 'Ayşe Yılmaz',
    siparisiAlan: 'Zeynep',
    urun: 'Lavaş Arası Tavuk Döner',
    urunGrubu: 'Dürüm',
    miktar: 2,
    fiyat: 165,
    toplam: 330,
    telefon: '0532 111 22 33',
    teslimEden: 'Mehmet K.',
    sube: 'Merkez',
    departman: 'Paket',
  },
  {
    id: 'ps2',
    tarihSaat: gunOffset(0, 11, 22),
    musteriAdi: 'Ayşe Yılmaz',
    siparisiAlan: 'Zeynep',
    urun: 'Kola (330 Ml.)',
    urunGrubu: 'İçecek',
    miktar: 2,
    fiyat: 45,
    toplam: 90,
    telefon: '0532 111 22 33',
    teslimEden: 'Mehmet K.',
    sube: 'Merkez',
    departman: 'Paket',
  },
  {
    id: 'ps3',
    tarihSaat: gunOffset(0, 12, 45),
    musteriAdi: 'Can Demir',
    siparisiAlan: 'Ahmet',
    urun: 'Mega Tavuk Döner Menü',
    urunGrubu: 'Döner Menü',
    miktar: 1,
    fiyat: 285,
    toplam: 285,
    telefon: '0544 987 65 43',
    teslimEden: 'Ali V.',
    sube: 'Merkez',
    departman: 'Paket',
  },
  {
    id: 'ps4',
    tarihSaat: gunOffset(0, 14, 10),
    musteriAdi: 'Trendyol #48291',
    siparisiAlan: 'Elif',
    urun: 'Zurna Et Döner Menü',
    urunGrubu: 'Döner Menü',
    miktar: 1,
    fiyat: 395,
    toplam: 395,
    telefon: '—',
    teslimEden: 'Kurye-3',
    sube: 'Merkez',
    departman: 'Trendyol',
  },
  {
    id: 'ps5',
    tarihSaat: gunOffset(0, 18, 30),
    musteriAdi: 'Fatma Koç',
    siparisiAlan: 'Murat',
    urun: 'İskender Et Döner',
    urunGrubu: 'Et Döner',
    miktar: 1,
    fiyat: 320,
    toplam: 320,
    telefon: '0505 222 33 44',
    teslimEden: 'Mehmet K.',
    sube: 'Merkez',
    departman: 'Paket',
  },
  {
    id: 'ps6',
    tarihSaat: gunOffset(0, 19, 5),
    musteriAdi: 'Fatma Koç',
    siparisiAlan: 'Murat',
    urun: 'Ayran (200 Ml.)',
    urunGrubu: 'İçecek',
    miktar: 1,
    fiyat: 35,
    toplam: 35,
    telefon: '0505 222 33 44',
    teslimEden: 'Mehmet K.',
    sube: 'Merkez',
    departman: 'Paket',
  },
  {
    id: 'ps7',
    tarihSaat: gunOffset(1, 20, 15),
    musteriAdi: 'Hakan Öztürk',
    siparisiAlan: 'Can',
    urun: 'Combo Zurna Tavuk Dürüm Menü',
    urunGrubu: 'Döner Menü',
    miktar: 2,
    fiyat: 375,
    toplam: 750,
    telefon: '0533 456 78 90',
    teslimEden: 'Ali V.',
    sube: 'Şube Kadıköy',
    departman: 'Paket',
  },
  {
    id: 'ps8',
    tarihSaat: gunOffset(1, 21, 50),
    musteriAdi: 'Yemeksepeti #11902',
    siparisiAlan: 'Elif',
    urun: 'Patates Kızartması',
    urunGrubu: 'Yan Ürün',
    miktar: 3,
    fiyat: 75,
    toplam: 225,
    telefon: '—',
    teslimEden: 'Kurye-1',
    sube: 'Şube Kadıköy',
    departman: 'Trendyol',
  },
  {
    id: 'ps9',
    tarihSaat: gunOffset(2, 13, 0),
    musteriAdi: 'Selin Arslan',
    siparisiAlan: 'Zeynep',
    urun: 'Baklava (3 Adet)',
    urunGrubu: 'Tatlı',
    miktar: 1,
    fiyat: 120,
    toplam: 120,
    telefon: '0542 333 44 55',
    teslimEden: 'Mehmet K.',
    sube: 'Merkez',
    departman: 'Paket',
  },
];
