import type { CariKayit } from '@/admin/baslat-menusu/cari-tanimlari/tipler';

export const varsayilanCariKaydi: CariKayit = {
  cariler: [
    {
      id: 1,
      kod: '0',
      ad: 'Nihai Tüketici',
      telefon: '',
      unvan: 'Nihai Tüketici',
      vergiNo: '',
      vergiDairesi: '',
      kartNo: '',
      iskontoOrani: '0',
      adres: '',
      ilce: '',
      il: '',
      kategori: 'Nihai Tüketici',
      ticariSicilNo: '',
      faturaAdi: '',
      faturaSoyadi: '',
      eposta: '',
      aktif: true,
      normalFaturaKullanicisi: false,
      kdvTevkifati: false,
    },
    {
      id: 2,
      kod: '111',
      ad: 'davut bozkurt',
      telefon: '05413826152',
      unvan: '',
      vergiNo: '',
      vergiDairesi: '',
      kartNo: '',
      iskontoOrani: '0',
      adres: '',
      ilce: '',
      il: '',
      kategori: '',
      ticariSicilNo: '',
      faturaAdi: '',
      faturaSoyadi: '',
      eposta: '',
      aktif: true,
      normalFaturaKullanicisi: false,
      kdvTevkifati: false,
    },
    {
      id: 3,
      kod: '112',
      ad: 'Enes Kazankaya',
      telefon: '+905444212715',
      unvan: '',
      vergiNo: '',
      vergiDairesi: '',
      kartNo: '',
      iskontoOrani: '0',
      adres: '',
      ilce: '',
      il: '',
      kategori: '',
      ticariSicilNo: '',
      faturaAdi: '',
      faturaSoyadi: '',
      eposta: '',
      aktif: true,
      normalFaturaKullanicisi: false,
      kdvTevkifati: false,
    },
    {
      id: 4,
      kod: '113',
      ad: 'Tuana K.',
      telefon: '05321234567',
      unvan: '',
      vergiNo: '',
      vergiDairesi: '',
      kartNo: '',
      iskontoOrani: '0',
      adres: '',
      ilce: '',
      il: '',
      kategori: '',
      ticariSicilNo: '',
      faturaAdi: '',
      faturaSoyadi: '',
      eposta: '',
      aktif: true,
      normalFaturaKullanicisi: false,
      kdvTevkifati: false,
    },
    {
      id: 5,
      kod: '114',
      ad: 'Mehmet Yılmaz',
      telefon: '05551234567',
      unvan: '',
      vergiNo: '',
      vergiDairesi: '',
      kartNo: '4521',
      iskontoOrani: '5',
      adres: 'Atatürk Cad. No:12',
      ilce: 'Kadıköy',
      il: 'İstanbul',
      kategori: 'Bireysel',
      ticariSicilNo: '',
      faturaAdi: 'Mehmet',
      faturaSoyadi: 'Yılmaz',
      eposta: 'mehmet@ornek.com',
      aktif: false,
      normalFaturaKullanicisi: true,
      kdvTevkifati: false,
    },
  ],
};
