import type { TahsilatTaramaSatiri } from '@/admin/baslat-menusu/paket-servisi-raporlari/ps-eski-tahsilat-tarama/tipler';

export const ORNEK_TAHSILATLAR: TahsilatTaramaSatiri[] = [
  {
    id: 't1',
    personel: 'Mehmet K.',
    toplamTeslimEdilen: 4850,
    nakitTahsilat: 2120,
    krediTahsilat: 1980,
    yCekTahsilat: 450,
    toplamTahsilat: 4550,
    acikHesap: 180,
    discount: 120,
    kalan: 0,
    sube: 'Merkez',
    departman: 'Paket',
  },
  {
    id: 't2',
    personel: 'Ali V.',
    toplamTeslimEdilen: 3620,
    nakitTahsilat: 1540,
    krediTahsilat: 1680,
    yCekTahsilat: 200,
    toplamTahsilat: 3420,
    acikHesap: 95,
    discount: 105,
    kalan: 0,
    sube: 'Merkez',
    departman: 'Paket',
  },
  {
    id: 't3',
    personel: 'Zeynep',
    toplamTeslimEdilen: 1280,
    nakitTahsilat: 420,
    krediTahsilat: 760,
    yCekTahsilat: 0,
    toplamTahsilat: 1180,
    acikHesap: 60,
    discount: 40,
    kalan: 0,
    sube: 'Merkez',
    departman: 'Trendyol',
  },
  {
    id: 't4',
    personel: 'Kurye-1',
    toplamTeslimEdilen: 2940,
    nakitTahsilat: 980,
    krediTahsilat: 1760,
    yCekTahsilat: 0,
    toplamTahsilat: 2740,
    acikHesap: 120,
    discount: 80,
    kalan: 0,
    sube: 'Şube Kadıköy',
    departman: 'Paket',
  },
  {
    id: 't5',
    personel: 'Kurye-3',
    toplamTeslimEdilen: 2150,
    nakitTahsilat: 650,
    krediTahsilat: 1320,
    yCekTahsilat: 80,
    toplamTahsilat: 2050,
    acikHesap: 70,
    discount: 30,
    kalan: 0,
    sube: 'Şube Kadıköy',
    departman: 'Trendyol',
  },
];
